version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"  # Streamlit
      - "8000:8000"  # FastAPI
    volumes:
      - ./data:/app/data
      - ./MLmodels:/app/MLmodels
    environment:
      - PYTHONUNBUFFERED=1
      - MAPBOX_API_KEY=${MAPBOX_API_KEY}
    restart: unless-stopped