version: '3.8'

services:
  ml-enedis:
    build: .
    container_name: ml-enedis-app
    ports:
      # Seulement Streamlit est expos√©
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./MLModels:/app/MLModels
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - FASTAPI_HOST=127.0.0.1
      - FASTAPI_PORT=8000
    networks:
      - internal

networks:
  internal:
    driver: bridge