version: '3.8'

services:
  ml-enedis:
    build: .
    container_name: ml-enedis-app
    ports:
      # Streamlit et FastAPI sont expos√©s
      - "8501:8501"
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./MLModels:/app/MLModels
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - FASTAPI_HOST=0.0.0.0
      - FASTAPI_PORT=8000
      - MAPBOX_API_KEY=${MAPBOX_API_KEY}
    networks:
      - internal

networks:
  internal:
    driver: bridge